"""update_resume

Revision ID: 779df2927f74
Revises: 415e2b70b19c
Create Date: 2026-06-18 14:09:21.916879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '779df2927f74'
down_revision: Union[str, Sequence[str], None] = '415e2b70b19c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('resumes_vacancy_id_fkey', 'resumes', type_='foreignkey')
    op.drop_column('resumes', 'vacancy_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('vacancy_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('resumes_vacancy_id_fkey', 'resumes', 'vacancies', ['vacancy_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
