"""changed resumes user connection

Revision ID: a5251bdcce5c
Revises: 0002_resume_vacancy_id
Create Date: 2026-06-18 10:48:11.467825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5251bdcce5c'
down_revision: Union[str, Sequence[str], None] = '0002_resume_vacancy_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('applicant_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'resumes', 'users', ['applicant_id'], ['id'], ondelete='SET NULL')
    op.drop_column('resumes', 'applicant_email')
    op.drop_column('resumes', 'applicant_name')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.add_column('resumes', sa.Column('applicant_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('resumes', sa.Column('applicant_email', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.drop_column('resumes', 'applicant_id')
    # ### end Alembic commands ###
